version: "3"

services:
  ### DB ################################################
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: db0,db1,db2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init-multi-postgres-databases.sh:/docker-entrypoint-initdb.d/init-multi-postgres-databases.sh
    ports:
      - "5432:5432"

  ### Redis ################################################
  redis:
    build: ./redis
    volumes:
      - ./.data/redis:/data
    ports:
      - "6379:6379"
